### ISSUE TITLE
page visit metrics

### ISSUE THREAD

**Issue by clyne** [ProjectPythia/projectpythia.github.io#114]
We need to be able to gather metrics on visits to Project Pythia. Ideally this would be done in a way that allows us to spot trends over time and the breadth of pythia content. I.e. tracking the number of visits to each page on a daily or weekly basis.

**Comment by brian-rose** [comment]
I was thinking the same thing. A simple way to do this is with Google analytics. Straightforward to add this to our sites, e.g.
https://jupyterbook.org/customize/config.html
shows how/where to set the `google_analytics_id` in our Foundations config

**Comment by clyne** [comment]
I think the GeoCAT team, cc'ing @erogluorhan, has experience with this.

**Comment by kmpaul** [comment]
@brian-rose @clyne 

Ok.  So, it turns out that I already enabled Google Analytics to the Portal site.  It was done by simply adding a `layout.html` file to the `/contents/_templates/` directory that added the correct HTML metadata tags and scripting to the site when Sphinx builds it.  The same thing would need to be done for the Foundations page.

When I created the new landing page (#115), though, I forgot about this.  So, I just opened PR #120 to fix this.

**Comment by kmpaul** [comment]
@clyne @dopplershift:  I have added both of your (using your UCAR Google addresses) to have access to the Pythia Portal Google Analytics page.  You should receive an email with instructions for access.

@brian-rose @ktyle:  I think I need to find your Google account email addresses to add the both of you.  I will try to find them and add them shortly.

**Comment by dopplershift** [comment]
Thanks @kmpaul

**Comment by kmpaul** [comment]
@brian-rose @ktyle:  For some reason, when I add the same email address that are on the Project Pythia Google Calendar events, the Google Analytics page says "Failed to register new users."  Do you both have separate Google accounts that are not ties to your Albany accounts that I can add to the Google Analytics project?  If so, send them to me in a separate email.

**Comment by kmpaul** [comment]
@ktyle:  Turns out that when I try to add your Albany email address, it changes it to a Gmail address saying that the Albany address was found as a "secondary address for another Google Account."  So, I *hope* that you get an email to your Gmail address (I won't post it here) and find you now have access to the Google Analytics account.

@brian-rose:  I think I will need a Google account to give you access.

@ProjectPythia/education @ProjectPythia/core @ProjectPythia/infrastructure:  Anyone else want access to the Google Analytics account?

**Comment by brian-rose** [comment]
@kmpaul I just emailed you my google account details

**Comment by ktyle** [comment]
@kmpaul I got it!

**Comment by kmpaul** [comment]
@clyne @dopplershift @brian-rose @ktyle:  Ok.  You all have administrative privileges on the Project Pythia Google Analytics account.  So, you should be able to see all of the analytics data.

We need to do something similar for the Foundations page.

**Comment by clyne** [comment]
@kmpaul how do we access the analytics page (I did not receive an email)? Thanks.

**Comment by dopplershift** [comment]
https://analytics.google.com/ should get you there.
