### ISSUE TITLE
Add AMS recorded presentation

### ISSUE THREAD

**Issue by clyne** [ProjectPythia/projectpythia.github.io#27]
The recorded AMS presentation gives an overview of Project Pythia and should probably be accessible from the web site (not as educational content, but something for the "about project pythia"). This begs the question of where videos should live. Should we simply upload to youtube? Would it make sense to have a "Project Pythia" channel on YouTube? Is this more fodder for our contributors guide. The link to the AMS talk is here:

https://drive.google.com/file/d/1JfBDF978grhcdIKcRgpPUYD84tX2R9OL/view?usp=sharing

**Comment by jukent** [comment]
Nice talk @clyne ! I think it makes sense to include this video in the "about" section even if most videos live elsewhere. Can we directly imbed the google drive link into the page? I would love for the video to appear on the site instead of being a link.

I think Youtube would be great too. Would our videos have ads on them -- or is that only if Youtube is paying us?

**Comment by clyne** [comment]
I'm not really sure what all of tradeoffs would be between hosting videos  in google drive vs youtube, and would love to hear what others think. It is possible to mostly get around adds with youtube. The youtube content that is in the "NCAR VisLab" channel, https://www.youtube.com/user/ucarvets, does not play adds. It can also easily be embedded within a window as done here: https://visgallery.ucar.edu/present-and-future-climate-in-a-global-model/

**Comment by jukent** [comment]
That is good news. I am also interested in hearing opinions on the platform tradeoffs.
